# CNN CONSTANTS
DATA_DIR = './data'
MODELS_DIR = '/cnn_models'
PERF_DIR = '/cnn_performance_data'
RES_DIR = './ALL_RESULTS'
GAN_DIR = './data/GAN'
EPOCHS = 50
BATCH_SIZE = 64
IMG_SIZE = 28
WINDOW_SIZE = [1280, 640]
IMGS_AMOUNT = 5000
VAL_SPLIT = 0.2

# GAN CONSTANTS
GAN_LATENT_SIZE = 64
GAN_HIDDEN_SIZE = 256
GAN_IMAGE_SIZE = 28*28
GAN_NUM_EPOCHS = 1000
GAN_BATCH_SIZE = 64
GAN_MNIST_TRAINING_SIZE = 10000
GAN_SAMPLES_DIR = './GAN_RESULTS/GAN_SAMPLES/samples'
GAN_SAVE_DIR = './GAN_RESULTS/GAN_SAVES/save'
GAN_MODEL_DIR = GAN_SAVE_DIR + '/model'
GAN_DATA_DIR = "./data/GAN"

