DATA_DIR = '../data'
MODELS_DIR = '../models'
PERF_DIR = '../performance_data'
RES_DIR = '../results'
GAN_DIR = 'network/data/GAN'
EPOCHS = 50
BATCH_SIZE = 64
IMG_SIZE = 28
WINDOW_SIZE = [1280, 640]
IMGS_AMOUNT = 10000
VAL_SPLIT = 0.2